### ISSUE TITLE
缺乏报错处理问题

### ISSUE THREAD

**Issue by WEN0797** [Guowenxuan1031/Saweima#1]
运行环境
windows11 1920*1080 amd64
PyAutoGUI Version: 0.9.54
Python 3.12.4

运行目录 资源文件目录均已修改

初次使用 sopping部分报错

Traceback (most recent call last):
  File "d:\swm\SAWEIMA.py", line 385, in <module>
    shopping()
  File "d:\swm\SAWEIMA.py", line 352, in shopping
    juice1 = pyautogui.locateOnScreen('D:\\swm\\juice1.png', confidence=0.85, region=(465,725,588-465,798-725))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wen0797\AppData\Roaming\Python\Python312\site-packages\pyautogui\__init__.py", line 174, in wrapper
    raise ImageNotFoundException  # Raise PyAutoGUI's ImageNotFoundException.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyautogui.ImageNotFoundException

购买图片未找到 代码执行停止

注释该部分继续运行

Traceback (most recent call last):
  File "d:\swm\SAWEIMA.py", line 398, in <module>
    prepare()
    ^^^^^^^^^
  File "d:\swm\SAWEIMA.py", line 144, in prepare
    if(InterruptTime() or InterruptDay()):
       ^^^^^^^^^^^^^^^
  File "d:\swm\SAWEIMA.py", line 318, in InterruptTime
    timelast = pyautogui.locateOnScreen('D:\\swm\\timelast.png', confidence=0.90, region=(218,101,379-218,210-101))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wen0797\AppData\Roaming\Python\Python312\site-packages\pyautogui\__init__.py", line 174, in wrapper
    raise ImageNotFoundException  # Raise PyAutoGUI's ImageNotFoundException.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyautogui.ImageNotFoundException

timelast未找到 停止运行

加入try 以catch except

程序无法正确执行制作沙威玛只会不停serve

**Comment by MarsTLBAD** [comment]
filenames = os.listdir('E:\\Saweima')
root = 'E:\\Saweima'

我看作者的游戏路径是E盘诶，
是不是应该要把游戏路径也挪到E盘？

**Comment by GodotR** [comment]
ok我解决问题了，请把环境配置到python==3.9，pyscreeze==0.1.18，pyautogui==0.9.38
——————————————————————————————————————————
同样的问题，我找到了这个
来自pyautogui的文档
NOTE: As of version 0.9.41, if the locate functions can’t find the provided image, they’ll raise ImageNotFoundException instead of returning None.
我重新安装了0.9.40版本的pyautogui，报错变成了couldNotImportPyScreeze() got an unexpected keyword argument 'confidence'
